"""Make obligation_logs notes and event_metadata nullable

Revision ID: 86645f9b3c3f
Revises: 370790c8b113
Create Date: 2026-01-12 15:47:28.507324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86645f9b3c3f'
down_revision: Union[str, Sequence[str], None] = '370790c8b113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('obligation_logs', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('obligation_logs', 'event_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('obligation_logs', 'event_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('obligation_logs', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
